### ISSUE TITLE
Build Prototype stage and camera

### ISSUE THREAD

**Issue by rdpolarity** [rdpolarity/ProjectBigmode#2]
**AC1**
GIVEN a player
WHEN the game has been started
THEN display a plane or stage that they can walk along

![Image](https://github.com/rdpolarity/ProjectBigmode/assets/17543653/61bec82c-61f4-44f5-8efb-ff1323a90c3c)
*In this scenario the stage is the 'black' tiles in the background.*

**Notes:**
- Have a look into how unity does 'tilemaps'. As this is how we will integrate the stage floor with pixel art
- Maybe make a super quick prototype pixel art of a swampy floor to test with (timeboxed haha)

**AC2**
GIVEN a player
WHEN the game has started
THEN ensure the camera is topdown
AND is capable of following/tracking the player

**Notes:**
- It may be good to look into the 'Cinemachine' plugin. Some of this logic I believe is built in ^^
- Given we may not have a player entity yet to test the camera tracking. Try and use a rough player prototype and make the camera target easily interchangeable.

**AC3**
GIVEN a player
WHEN the game has started
THEN ensure the camera angle matches a similar style perspective angle style to cult of the lamb

![Image](https://github.com/rdpolarity/ProjectBigmode/assets/17543653/dc3e988b-a4e1-4791-ba90-2d027314503d)
*Reference above*

**Notes:**
- It doesn't have to match perfectly and we may revert on the style but it'd be good to build the game around that angle early

**Comment by FathomlessFunction** [comment]
Missed the pixel art bit! Wanted to see if I could doodle tiles, so I've made some placeholders until we get the pixelly ones.
I think parts 1 and 3 of this are both done now. Next is just the camera tracking.
(Angle might need to be adjusted, not sure. That seems chill enough to do though c: )


![Image](https://github.com/rdpolarity/ProjectBigmode/assets/19755210/7b3c1461-c9b8-49d5-be0c-094bfcb5dca0)
